version: '3.8'

services:
  php:
    image: gek22/php-app:latest
    container_name: php-app
    volumes:
      - .:/var/www/html

  nginx:
    image: gek22/nginx-custom:latest
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - php
